<?php

return [
    'default' => [
        'version' => 1,
        'title' => 'Formulaire de candidature',
        'description' => 'Renseignez les informations demandées pour soumettre votre projet.',
        'submit_label' => 'Soumettre ma candidature',
        'success_message' => 'Votre candidature a été envoyée avec succès.',
        'steps' => [
            [
                'key' => 'identity',
                'title' => 'Profil de la candidate',
                'description' => 'Vos informations personnelles, votre pays, votre ville et vos coordonnées.',
            ],
            [
                'key' => 'project',
                'title' => 'Projet et motivation',
                'description' => 'Présentez votre projet, votre expérience et les éléments de sélection.',
            ],
            [
                'key' => 'documents',
                'title' => 'Pièces justificatives',
                'description' => 'Téléchargez les documents et finalisez votre dossier.',
            ],
        ],
        'fields' => [
            [
                'key' => 'full_name',
                'type' => 'text',
                'label' => 'Nom complet | Full name',
                'required' => true,
                'autocomplete' => 'name',
                'max_length' => 150,
                'step' => 'identity',
                'section' => 'personal_identity',
                'section_title' => 'Identité',
                'section_description' => 'Présentez-vous en quelques informations essentielles.',
                'column_span' => 1,
            ],
            [
                'key' => 'date_of_birth',
                'type' => 'date',
                'label' => 'Date de naissance | Date of birth',
                'required' => true,
                'step' => 'identity',
                'section' => 'personal_identity',
                'column_span' => 1,
            ],
            [
                'key' => 'age',
                'type' => 'number',
                'label' => 'Age',
                'required' => true,
                'min' => 10,
                'max' => 120,
                'step' => 'identity',
                'section' => 'personal_identity',
                'column_span' => 1,
            ],
            [
                'key' => 'nationality',
                'type' => 'country',
                'label' => 'Nationalité | Nationality',
                'required' => true,
                'step' => 'identity',
                'section' => 'location',
                'section_title' => 'Localisation et contact',
                'section_description' => 'Choisissez des références pays, ville et téléphone cohérentes.',
                'column_span' => 1,
            ],
            [
                'key' => 'country_of_residence',
                'type' => 'country',
                'label' => 'Pays de résidence | Country of residence',
                'required' => true,
                'step' => 'identity',
                'section' => 'location',
                'column_span' => 1,
            ],
            [
                'key' => 'city_of_residence',
                'type' => 'city',
                'label' => 'Ville | Town',
                'required' => true,
                'country_field' => 'country_of_residence',
                'step' => 'identity',
                'section' => 'location',
                'column_span' => 1,
            ],
            [
                'key' => 'whatsapp_number',
                'type' => 'phone',
                'label' => 'Numéro WhatsApp | Whatsapp number',
                'required' => true,
                'country_field' => 'country_of_residence',
                'step' => 'identity',
                'section' => 'location',
                'column_span' => 1,
            ],
            [
                'key' => 'email',
                'type' => 'email',
                'label' => 'E-mail',
                'required' => true,
                'autocomplete' => 'email',
                'max_length' => 190,
                'step' => 'identity',
                'section' => 'location',
                'column_span' => 1,
            ],
            [
                'key' => 'academic_achievement',
                'type' => 'text',
                'label' => 'Niveau d\'étude | Academic achievement',
                'required' => true,
                'max_length' => 255,
                'step' => 'project',
                'section' => 'candidate_background',
                'section_title' => 'Parcours et présentation',
                'section_description' => 'Mettez en avant votre profil et votre expérience.',
                'column_span' => 1,
            ],
            [
                'key' => 'biography',
                'type' => 'textarea',
                'label' => 'Biographie (10 phrases max) | Biography (10 sentences max)',
                'required' => true,
                'max_length' => 1500,
                'step' => 'project',
                'section' => 'candidate_background',
                'column_span' => 2,
            ],
            [
                'key' => 'project_title',
                'type' => 'text',
                'label' => 'Titre du projet | Project title',
                'required' => true,
                'max_length' => 255,
                'step' => 'project',
                'section' => 'project_overview',
                'section_title' => 'Présentation du projet',
                'section_description' => 'Décrivez clairement le projet présenté à l\'appel.',
                'column_span' => 2,
            ],
            [
                'key' => 'project_poster',
                'type' => 'file',
                'label' => 'Veuillez télécharger une affiche de votre projet | Please upload a poster of your project',
                'required' => true,
                'accept' => ['image/jpeg', 'image/png', 'image/webp'],
                'max_size_mb' => 1,
                'step' => 'documents',
                'section' => 'project_assets',
                'section_title' => 'Documents du projet',
                'section_description' => 'Ajoutez les pièces visuelles et administratives du dossier.',
                'column_span' => 1,
            ],
            [
                'key' => 'pitch',
                'type' => 'textarea',
                'label' => 'Pitch (1 phrase) | Pitch (1 sentence)',
                'required' => true,
                'max_length' => 280,
                'step' => 'project',
                'section' => 'project_overview',
                'column_span' => 2,
            ],
            [
                'key' => 'pitch_video',
                'type' => 'file',
                'label' => 'Veuillez télécharger une vidéo de vous en train de pitcher votre projet (2 min max) | Please upload a video of you pitching your project (2 min max)',
                'required' => true,
                'accept' => ['video/mp4', 'video/quicktime', 'video/webm'],
                'max_size_mb' => 10,
                'step' => 'documents',
                'section' => 'project_assets',
                'column_span' => 1,
            ],
            [
                'key' => 'synopsis',
                'type' => 'textarea',
                'label' => 'Synopsis (5 phrases) | Synopsis (5 sentences)',
                'required' => true,
                'max_length' => 1500,
                'step' => 'project',
                'section' => 'project_overview',
                'column_span' => 2,
            ],
            [
                'key' => 'film_genre',
                'type' => 'radio',
                'label' => 'Quel est le genre de votre film ? | What is the genre of your film?',
                'required' => true,
                'step' => 'project',
                'section' => 'project_positioning',
                'section_title' => 'Positionnement du projet',
                'section_description' => 'Précisez les caractéristiques clés de votre projet.',
                'column_span' => 2,
                'options' => [
                    ['value' => 'drama', 'label' => 'Drame / Drama'],
                    ['value' => 'comedy', 'label' => 'Comédie / Comedy'],
                    ['value' => 'action', 'label' => 'Action'],
                    ['value' => 'horror', 'label' => 'Horreur / Horror'],
                    ['value' => 'sci_fi', 'label' => 'Science-fiction (SF) / Sci-Fi'],
                    ['value' => 'crime', 'label' => 'Policier / Crime'],
                    ['value' => 'thriller', 'label' => 'Thriller'],
                    ['value' => 'romance', 'label' => 'Romance'],
                    ['value' => 'fantasy', 'label' => 'Fantastique / Fantasy'],
                    ['value' => 'musical', 'label' => 'Musical'],
                    ['value' => 'animation', 'label' => 'Animation'],
                    ['value' => 'western', 'label' => 'Western'],
                    ['value' => 'war', 'label' => 'Guerre / War'],
                    ['value' => 'documentary', 'label' => 'Documentaire / Documentary'],
                ],
            ],
            [
                'key' => 'owns_all_rights',
                'type' => 'boolean',
                'label' => 'Détenez vous tous les droits du projet | Do you own all the rights of this project?',
                'required' => true,
                'step' => 'project',
                'section' => 'project_positioning',
                'column_span' => 1,
            ],
            [
                'key' => 'has_producer',
                'type' => 'boolean',
                'label' => 'Avez vous un producteur associé au projet ? | Does your project have a producer?',
                'required' => true,
                'step' => 'project',
                'section' => 'project_positioning',
                'column_span' => 1,
            ],
            [
                'key' => 'film_experience',
                'type' => 'textarea',
                'label' => 'Parlez nous de votre expérience avec le cinéma ? | Can you tell us about your experience in the film industry?',
                'required' => true,
                'max_length' => 2000,
                'step' => 'project',
                'section' => 'motivation',
                'section_title' => 'Motivation',
                'section_description' => 'Expliquez votre parcours et pourquoi vous correspondez au programme.',
                'column_span' => 2,
            ],
            [
                'key' => 'ideal_candidate',
                'type' => 'textarea',
                'label' => 'Pourquoi êtes vous la candidate idéale pour ce programme? | Why are you the ideal candidate for this program?',
                'required' => true,
                'max_length' => 2000,
                'step' => 'project',
                'section' => 'motivation',
                'column_span' => 2,
            ],
            [
                'key' => 'profile_photo',
                'type' => 'file',
                'label' => 'Veuillez télécharger une photo de vous | Please upload a picture of you',
                'required' => true,
                'accept' => ['image/jpeg', 'image/png', 'image/webp'],
                'max_size_mb' => 1,
                'step' => 'documents',
                'section' => 'identity_documents',
                'section_title' => 'Pièces d\'identité',
                'section_description' => 'Vérifiez que les fichiers transmis sont lisibles et au bon format.',
                'column_span' => 1,
            ],
            [
                'key' => 'identity_document',
                'type' => 'file',
                'label' => 'Veuillez télécharger une copie de votre passport ou CNI | Please upload a copie of your passport or national ID card',
                'required' => true,
                'accept' => ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
                'max_size_mb' => 10,
                'step' => 'documents',
                'section' => 'identity_documents',
                'column_span' => 1,
            ],
            [
                'key' => 'payment_receipt',
                'type' => 'file',
                'label' => 'Veuillez télécharger la preuve de paiement si elle est requise | Please upload your payment receipt if required',
                'required' => false,
                'accept' => ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
                'max_size_mb' => 10,
                'step' => 'documents',
                'section' => 'payment_and_validation',
                'section_title' => 'Validation finale',
                'section_description' => 'Ajoutez la preuve de paiement si elle est demandée, puis confirmez votre soumission.',
                'column_span' => 2,
            ],
            [
                'key' => 'discovery_channels',
                'type' => 'checkbox_group',
                'label' => 'Où avez vous entendu parlé de ce programme ? | Where did you hear about this program?',
                'required' => true,
                'step' => 'documents',
                'section' => 'payment_and_validation',
                'column_span' => 2,
                'options' => [
                    ['value' => 'facebook', 'label' => 'Facebook'],
                    ['value' => 'instagram', 'label' => 'Instagram'],
                    ['value' => 'youtube', 'label' => 'Youtube'],
                    ['value' => 'linkedin', 'label' => 'LinkedIn'],
                    ['value' => 'on_move_magazine', 'label' => 'On Move magazine'],
                    ['value' => 'ong_yerda', 'label' => 'ONG YERDA'],
                    ['value' => 'newsletter', 'label' => 'Newsletter'],
                    ['value' => 'other', 'label' => 'Autre / Other'],
                ],
            ],
            [
                'key' => 'terms_accepted',
                'type' => 'boolean',
                'label' => 'Terme et condition | Terms & conditions',
                'required' => true,
                'must_be_true' => true,
                'true_label' => 'J\'accepte tous les termes et conditions du programme | I accept all the terms and conditions of the program',
                'false_label' => 'Je n\'accepte pas tous les termes et conditions du programme | I don\'t accept all terms and conditions of the program',
                'step' => 'documents',
                'section' => 'payment_and_validation',
                'column_span' => 2,
            ],
        ],
    ],
];
