<?php

namespace App\Support\Rbac;

class PermissionCatalog
{
    public static function platformPermissions(): array
    {
        return [
            'platform.access',
            'platform.tenants.view',
            'platform.tenants.create',
            'platform.tenants.update',
            'platform.tenants.delete',
            'platform.platform_users.view',
            'platform.platform_users.create',
            'platform.platform_users.update',
            'platform.platform_users.delete',
            'platform.roles.view',
            'platform.roles.create',
            'platform.roles.update',
            'platform.roles.delete',
            'platform.platform_settings.view',
            'platform.platform_settings.create',
            'platform.platform_settings.update',
            'platform.platform_settings.delete',
            'platform.plans.view',
            'platform.plans.create',
            'platform.plans.update',
            'platform.plans.delete',
            'platform.subscriptions.view',
            'platform.subscriptions.create',
            'platform.subscriptions.update',
            'platform.subscriptions.delete',
            'platform.commercial_policies.view',
            'platform.commercial_policies.create',
            'platform.commercial_policies.update',
            'platform.commercial_policies.delete',
            'platform.categories.view',
            'platform.categories.create',
            'platform.categories.update',
            'platform.categories.delete',
            'platform.tags.view',
            'platform.tags.create',
            'platform.tags.update',
            'platform.tags.delete',
            'platform.references.view',
            'platform.references.create',
            'platform.references.update',
            'platform.references.delete',
            'platform.feature_flags.view',
            'platform.feature_flags.create',
            'platform.feature_flags.update',
            'platform.feature_flags.delete',
            'platform.payment_gateways.view',
            'platform.payment_gateways.create',
            'platform.payment_gateways.update',
            'platform.payment_gateways.delete',
            'platform.compliance_policies.view',
            'platform.compliance_policies.create',
            'platform.compliance_policies.update',
            'platform.compliance_policies.delete',
            'platform.transactions.view',
            'platform.transactions.create',
            'platform.transactions.update',
            'platform.transactions.delete',
            'platform.payment_incidents.view',
            'platform.payment_incidents.create',
            'platform.payment_incidents.update',
            'platform.payment_incidents.delete',
            'platform.settlements.view',
            'platform.settlements.create',
            'platform.settlements.update',
            'platform.settlements.delete',
            'platform.payout_batches.view',
            'platform.payout_batches.create',
            'platform.payout_batches.update',
            'platform.payout_batches.delete',
            'platform.reconciliation_logs.view',
            'platform.reconciliation_logs.create',
            'platform.reconciliation_logs.update',
            'platform.reconciliation_logs.delete',
            'platform.financial_exports.view',
            'platform.financial_exports.create',
            'platform.financial_exports.update',
            'platform.financial_exports.delete',
            'platform.kpi_snapshots.view',
            'platform.kpi_snapshots.create',
            'platform.kpi_snapshots.update',
            'platform.kpi_snapshots.delete',
            'platform.webhook_logs.view',
            'platform.webhook_logs.create',
            'platform.webhook_logs.update',
            'platform.webhook_logs.delete',
            'platform.support_tickets.view',
            'platform.support_tickets.create',
            'platform.support_tickets.update',
            'platform.support_tickets.delete',
            'platform.incidents.view',
            'platform.incidents.create',
            'platform.incidents.update',
            'platform.incidents.delete',
            'platform.audit_logs.view',
        ];
    }

    public static function tenantPermissions(): array
    {
        return [
            'tenant.access',
            'tenant.users.view',
            'tenant.users.create',
            'tenant.users.update',
            'tenant.users.delete',
            'tenant.roles.view',
            'tenant.roles.create',
            'tenant.roles.update',
            'tenant.roles.delete',
            'tenant.settings.view',
            'tenant.settings.update',
            'tenant.catalog.view',
            'tenant.catalog.update',
            'tenant.support.view',
            'tenant.support.create',
            'tenant.support.update',
            'tenant.finance.view',
            'tenant.audit.view',
        ];
    }

    public static function platformRoles(): array
    {
        return [
            'super-admin' => self::platformPermissions(),
            'platform-ops' => [
                'platform.access',
                'platform.tenants.view',
                'platform.tenants.create',
                'platform.tenants.update',
                'platform.platform_settings.view',
                'platform.platform_settings.update',
                'platform.feature_flags.view',
                'platform.feature_flags.update',
                'platform.payment_gateways.view',
                'platform.payment_gateways.update',
                'platform.compliance_policies.view',
                'platform.compliance_policies.update',
                'platform.support_tickets.view',
                'platform.support_tickets.update',
                'platform.incidents.view',
                'platform.incidents.update',
                'platform.audit_logs.view',
            ],
            'finance-manager' => [
                'platform.access',
                'platform.plans.view',
                'platform.subscriptions.view',
                'platform.subscriptions.create',
                'platform.subscriptions.update',
                'platform.subscriptions.delete',
                'platform.commercial_policies.view',
                'platform.transactions.view',
                'platform.transactions.update',
                'platform.payment_incidents.view',
                'platform.payment_incidents.update',
                'platform.settlements.view',
                'platform.settlements.create',
                'platform.settlements.update',
                'platform.payout_batches.view',
                'platform.payout_batches.create',
                'platform.payout_batches.update',
                'platform.reconciliation_logs.view',
                'platform.reconciliation_logs.create',
                'platform.financial_exports.view',
                'platform.financial_exports.create',
                'platform.kpi_snapshots.view',
                'platform.webhook_logs.view',
            ],
            'support-manager' => [
                'platform.access',
                'platform.support_tickets.view',
                'platform.support_tickets.create',
                'platform.support_tickets.update',
                'platform.incidents.view',
                'platform.incidents.create',
                'platform.incidents.update',
                'platform.audit_logs.view',
            ],
        ];
    }

    public static function tenantRoles(): array
    {
        return [
            'owner' => self::tenantPermissions(),
            'manager' => [
                'tenant.access',
                'tenant.users.view',
                'tenant.users.create',
                'tenant.users.update',
                'tenant.roles.view',
                'tenant.settings.view',
                'tenant.settings.update',
                'tenant.catalog.view',
                'tenant.catalog.update',
                'tenant.support.view',
                'tenant.support.update',
                'tenant.finance.view',
                'tenant.audit.view',
            ],
            'finance' => [
                'tenant.access',
                'tenant.finance.view',
                'tenant.audit.view',
            ],
            'support' => [
                'tenant.access',
                'tenant.support.view',
                'tenant.support.create',
                'tenant.support.update',
            ],
            'analyst' => [
                'tenant.access',
                'tenant.audit.view',
                'tenant.finance.view',
                'tenant.catalog.view',
            ],
        ];
    }
}
